### ISSUE TITLE
Buy/Sell are not the same as Open/Close Order/Position 

### ISSUE THREAD

**Issue by the-ilgar-roshen** [the-ilgar-roshen/forex-like-binance#1]
Selling is not Closing an order [selling is a different type of order]. 
The amount/quantity of an asset adds-up to the balance of that particular asset (crypto-currency). 

> Each crypto-currency has its own asset balance 
> That [also] makes the difference between Forex and Spot trading on Crypto-Exchange 

Bought some amount of coins - the **Order** with a type **BUY** was **FILLED** 
and the quantity of units (coins) adds-up to the total number of units stored in it's own asset balance. 
Sold some amount of coins - the **Order** with a type **SELL** was **FILLED** 
and it is same as subtracting the quantity of units (coins) 
from one asset balance and adding that to another asset balance. 

> This is not even [actual] buying/selling 
> This is an exchange of one asset with the other one 

There is no such thing as selling an order. 
Once the BUY type Order was FILLED, that's it ! 
The Order's job is Done [same as the order is being closed]. 

Needs to solve this [conceptual] issue 
in order to continue developing, designing and adding new features.

**Comment by ilgar-roshen** [comment]
Does sound like an issue when making a difference between buy/sell and open/close orders 
but Buy/Sell operations are not the cause of this issue. 
Changing a way of thinking about the issue related to a concept will may change understanding of the concept.

**Comment by the-ilgar-roshen** [comment]
What if there is no Buy or Sell and both are [like] the same exchange operation [just labeled differently] ?

**Comment by the-ilgar-roshen** [comment]
Forex and [this] Crypto Exchange are different. 
The Solution is to to adapt the concept [instead of making an issue out of difference|s]. 
At this point [mind unlocks and] it becomes easier to break the issue into steps.

### Simplify

Consider Buy and Sell [both] are being the same exchange of one asset with another one. 

### Something in common

Either Buy, Sell, Open or Close, these [actually] could perform the ~same exchange function. 
Function for each of them can do [the ~same]: an exchange of one asset with another one 

### Differentiate/Divide 

#### The difference between Buy/Sell and Open/Close is:

- If **Buying** on Spot Trading is about buying [with sufficient balance] a quantity of units for asset "A" 
then **Selling** on Spot Trading is about selling any available quantity of units for asset "A" 
- If **Opening** Order/Position on Spot Trading would be about buying quantity of units for asset "A" 
then **Closing** Order/Position on Spot Trading should mean selling that same quantity of units for asset "A"
